//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class countryList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public countryList()
        {
            this.filmEntry = new HashSet<filmEntry>();
        }
    
        public string countryCode { get; set; }
        public string countryNameEn { get; set; }
        public string countryNameHr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filmEntry> filmEntry { get; set; }

        public object ToJson()
        {

            StringBuilder sb = new StringBuilder();

            sb.Append($@"{{");
            sb.Append($@"""countryCode"":""{countryCode}"",");
            sb.Append($@"""countryNameEn"":""{countryNameEn}"",");
            sb.Append($@"""countryNameHr"":""{countryNameHr}""");
            sb.Append($@"}}");

            return sb.ToString();
        }
    }
}
