//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> userSet { get; set; }
        public virtual DbSet<role> roleSet { get; set; }
        public virtual DbSet<movieList> movieListSet { get; set; }
        public virtual DbSet<movieListEntry> movieListEntrySet { get; set; }
        public virtual DbSet<person> personSet { get; set; }
        public virtual DbSet<personInFilmEntry> personInFilmEntrySet { get; set; }
        public virtual DbSet<filmEntry> filmEntrySet { get; set; }
        public virtual DbSet<character> characterSet { get; set; }
        public virtual DbSet<actorDoingCharacter> actorDoingCharacterSet { get; set; }
        public virtual DbSet<image> imageSet { get; set; }
        public virtual DbSet<filmEntryHasGenre> filmEntryHasGenreSet { get; set; }
        public virtual DbSet<genre> genreSet { get; set; }
        public virtual DbSet<personRole> personRoleSet { get; set; }
    }
}
