//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmEntryHasGenre
    {
        public int Id { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual filmEntry filmEntry { get; set; }
    }
}
