//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmEntrySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filmEntrySet()
        {
            this.filmEntryHasGenreSet = new HashSet<filmEntryHasGenreSet>();
            this.personInFilmEntrySet = new HashSet<personInFilmEntrySet>();
            this.movieListEntrySet = new HashSet<movieListEntrySet>();
            this.imageSet = new HashSet<imageSet>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.TimeSpan duration { get; set; }
        public System.DateTime releaseDate { get; set; }
        public string status { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateLastUpdated { get; set; }
        public string countryOfOrigin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filmEntryHasGenreSet> filmEntryHasGenreSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personInFilmEntrySet> personInFilmEntrySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movieListEntrySet> movieListEntrySet { get; set; }
        public virtual filmEntrySet_movie filmEntrySet_movie { get; set; }
        public virtual filmEntrySet_tvShow filmEntrySet_tvShow { get; set; }
        public virtual filmEntrySet_tvShow filmEntrySet_tvShow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imageSet> imageSet { get; set; }
    }
}
