//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmEntryHasGenreSet
    {
        public int Id { get; set; }
        public int genre_Id { get; set; }
        public int filmEntry_Id { get; set; }
    
        public virtual filmEntrySet filmEntrySet { get; set; }
        public virtual genreSet genreSet { get; set; }
    }
}
