//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmEntry_tvShow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filmEntry_tvShow()
        {
            this.filmEntry1 = new HashSet<filmEntry>();
        }
    
        public Nullable<System.DateTime> dateFirstEpisodeAired { get; set; }
        public Nullable<System.DateTime> dateLastEpisodeAired { get; set; }
        public int Id { get; set; }
    
        public virtual filmEntry filmEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filmEntry> filmEntry1 { get; set; }
    }
}
