//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VjezbaEntities : DbContext
    {
        public VjezbaEntities()
            : base("name=VjezbaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actorDoingCharacterSet> actorDoingCharacterSet { get; set; }
        public virtual DbSet<characterSet> characterSet { get; set; }
        public virtual DbSet<filmEntryHasGenreSet> filmEntryHasGenreSet { get; set; }
        public virtual DbSet<filmEntrySet> filmEntrySet { get; set; }
        public virtual DbSet<filmEntrySet_movie> filmEntrySet_movie { get; set; }
        public virtual DbSet<filmEntrySet_tvShow> filmEntrySet_tvShow { get; set; }
        public virtual DbSet<genreSet> genreSet { get; set; }
        public virtual DbSet<imageSet> imageSet { get; set; }
        public virtual DbSet<movieListEntrySet> movieListEntrySet { get; set; }
        public virtual DbSet<movieListSet> movieListSet { get; set; }
        public virtual DbSet<personInFilmEntrySet> personInFilmEntrySet { get; set; }
        public virtual DbSet<personRoleSet> personRoleSet { get; set; }
        public virtual DbSet<personSet> personSet { get; set; }
        public virtual DbSet<roleSet> roleSet { get; set; }
        public virtual DbSet<userSet> userSet { get; set; }
    }
}
