//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vjezba_backend
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.movieList = new HashSet<movieList>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string passSalt { get; set; }
        public string passHash { get; set; }
        public bool verified { get; set; }
        public bool banned { get; set; }
        public string banReason { get; set; }
        public System.DateTime registrationTime { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthdate { get; set; }
        public string avatarLink { get; set; }
        public string role_roleName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movieList> movieList { get; set; }
        public virtual role role { get; set; }

        public object ToJson()
        {
            var x = new
            {
                username = username,
                firstName = firstName,
                lastName = lastName
            };
            return x;

    }
}
